//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDataBase.MovieData
{
    using System;
    using System.Collections.Generic;

    public partial class Movy
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Year { get; set; }

        public Movy()
        {
        }

        public Movy(int _id, string _name, string _genre, int _year = 0)
        {
            ID = _id;
            Name = _name;
            Genre = _genre;
            Year = _year;
        }
    }
}
