//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDataBase.MovieData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }

        public User()
        {
        }
        public User(string _email, string _username, string _password)
        {
            Email = _email;
            Username = _username;
            Password = _password;
        }

    }
}
